login.btn.login=Inciar sesi\u00f3n
login.lbl.user-name=Nombre de usuario
login.lbl.password=Contrase\u00f1a

sales.lbl.quantity=Cantidad
sales.lbl.bar-code=C\u00f3digo de barras / nombre (F3)
sales.lbl.fast-rest=Resta r\u00e1pida
sales.btn.complete=Completo
sales.btn.no-complete=Incompleto
sales.dlg.manual-search=B\u00fasqueda manual de un producto
sales.dlg.debtors=Deudores

sales-today.dialog.cancel-sale=Est\u00e1 por cancelar esta venta. \n \u00bfContinuar?
sales-today.dialog.reason-cancel=Por favor escribe el motivo de la baja

sales-report.lbl.init-date=Fecha inicio
sales-report.lbl.end-date=Fecha fin
sales-report.btn.filter-now=Filtrar ahora
sales-report.btn.download-report=Descargar reporte

stock.btn.download-stock=Descargar inventario completo
stock.lbl.product=Producto
stock.lbl.cost-of-sale=Costo de venta
stock.lbl.price=Precio
stock.lbl.quantity=Cantidad en existencia
stock.lbl.bar-code=C\u00f3digo de barras
stock.btn.cost-evolutions=Evoluci\u00f3n de costos
stock.btn.movements=Movimientos
stock.dlg.not-movements=No hay movimientos %s
stock.dlg.movements-history=Historial de movimientos de %s

register-product.lbl.bar-code=C\u00f3digo de barras
register-product.lbl.name=Nombre
register-product.lbl.by-kg=\u00bfPor kg?
register-product.lbl.quantity=Cantidad
register-product.lbl.price=Precio
register-product.lbl.cost-of-sale=Costo de venta

categories.lbl.category=Categor\u00eda
categories.lbl.description=Descripci\u00f3n
categories.lbl.edit-category=Editar categor\u00eda

cashbox.btn.close-now=Cerrar ahora
cashbox.dlg.import-from-notes=\u00bfImportar desde notas r\u00e1pidas?
cashbox.dlg.closing-cashbox=Cerrando caja de dinero

cashboxes.lbl.actives=Activos
cashboxes.lbl.costs=Gastos

notes.lbl.instructions=\u00a1Importante! \nRecuerda que si tu nota se cargar\u00e1 como activo / pasivo \ndebes colocar la cantidad comenzando por $
notes.btn.save-note=Guardar nota
notes.dlg.editing-note=Eitando nota

debtors.lbl.add-pay=Abonar
debtors.btn.pay-all=Pagar todo
debtors.lbl.debtor-debt=debe $%s
debtors.dlg.pay-all=\u00bfSeguro que deseas pagar toda la cuenta?

console.btn.download-logs=Descargar logs

common.lbl.total=Total: $%s
common.btn.save=Guardar
common.btn.save-now=Guardar ahora
common.btn.save-changes=Guardar cambios
common.btn.cancel=Cancelar
common.lbl.currency-symbol-before=$%s
common.btn.continue=Continuar
common.btn.close=Cerrar

dlg-debtors.btn-register=Registrar
dlg-debtors.lbl.give=Dej\u00f3
dlg-debtors.lbl.give-cash=%s deja 

dlg-cashbox.lbl.total-amount=Monto total de ventas
dlg-cashbox.lbl.description=Descripci\u00f3n
dlg-cashbox.lbl.amount=Monto
dlg-cashbox.lbl.total-actives=Total activos: %s
dlg-cashbox.lbl.total-costs=Total pasivos: %s
dlg-cashbox.lbl.neto-total=Total neto: %s

dlg-note.btn.delete=Eliminar nota

dlg-filter.lbl.filter=Filtrar

mobile-companies.lbl.company-name=Nombre de compa\u00f1\u00eda

top-ups.lbl.company-phone=Compa\u00f1\u00eda telef\u00f3nica
top-ups.lbl.phone-number=Numero de tel\u00e9fono
top-ups.lbl.amount=Monto de recarga
top-ups.btn.apply-filter=Aplicar filtro
top-ups.btn.close-now=Cerrar todo