package com.blo.sales.v2.config;

import com.blo.sales.v2.controller.IAccountsController;
import com.blo.sales.v2.controller.IActivesCostsController;
import com.blo.sales.v2.controller.ICashboxController;
import com.blo.sales.v2.controller.ICashboxesActivesCostsController;
import com.blo.sales.v2.controller.ICashboxesSalesController;
import com.blo.sales.v2.controller.ICategoriesController;
import com.blo.sales.v2.controller.IDBTransactionManagerController;
import com.blo.sales.v2.controller.IDebtorSettlementsController;
import com.blo.sales.v2.controller.IDebtorsController;
import com.blo.sales.v2.controller.IDebtorsSalesController;
import com.blo.sales.v2.controller.IFinancialHistoryController;
import com.blo.sales.v2.controller.IHistoryController;
import com.blo.sales.v2.controller.IMobileCompanyController;
import com.blo.sales.v2.controller.IPricesHistoryController;
import com.blo.sales.v2.controller.IProductsController;
import com.blo.sales.v2.controller.ISaleDeletedDetailController;
import com.blo.sales.v2.controller.ISalesController;
import com.blo.sales.v2.controller.ISalesProductController;
import com.blo.sales.v2.controller.IStockPricesHistoryController;
import com.blo.sales.v2.controller.ITopUpsController;
import com.blo.sales.v2.controller.IUserController;
import com.blo.sales.v2.controller.impl.AccountsControllerImpl;
import com.blo.sales.v2.controller.impl.ActivesCostsControllerImpl;
import com.blo.sales.v2.controller.impl.CashboxControllerImpl;
import com.blo.sales.v2.controller.impl.CashboxesActivesCostsControllerImpl;
import com.blo.sales.v2.controller.impl.CashboxesSalesControllerImpl;
import com.blo.sales.v2.controller.impl.CategoriesControllerImpl;
import com.blo.sales.v2.controller.impl.DBTransactionManagerControllerImpl;
import com.blo.sales.v2.controller.impl.DebtorSettlementsControllerImpl;
import com.blo.sales.v2.controller.impl.DebtorsControllerImpl;
import com.blo.sales.v2.controller.impl.DebtorsSalesControllerImpl;
import com.blo.sales.v2.controller.impl.FinancialHistoryControllerImpl;
import com.blo.sales.v2.controller.impl.HistoryControllerImpl;
import com.blo.sales.v2.controller.impl.MobileCompanyControllerImpl;
import com.blo.sales.v2.controller.impl.PricesHistoryControllerImpl;
import com.blo.sales.v2.controller.impl.ProductsControllerImpl;
import com.blo.sales.v2.controller.impl.SaleDeletedDetailControllerImpl;
import com.blo.sales.v2.controller.impl.SalesControllerImpl;
import com.blo.sales.v2.controller.impl.SalesProductControllerImpl;
import com.blo.sales.v2.controller.impl.StockPricesHistoryControllerImpl;
import com.blo.sales.v2.controller.impl.TopUpsControllerImpl;
import com.blo.sales.v2.controller.impl.UserControllerImpl;
import com.blo.sales.v2.model.IAccountsModel;
import com.blo.sales.v2.model.IActivesCostsModel;
import com.blo.sales.v2.model.ICashboxModel;
import com.blo.sales.v2.model.ICashboxesActivesCostsModel;
import com.blo.sales.v2.model.ICashboxesSalesModel;
import com.blo.sales.v2.model.ICategoriesModel;
import com.blo.sales.v2.model.IDebtorsModel;
import com.blo.sales.v2.model.IDebtorsSalesModel;
import com.blo.sales.v2.model.IHistoryModel;
import com.blo.sales.v2.model.IMobileCompanyModel;
import com.blo.sales.v2.model.IPricesHistoryModel;
import com.blo.sales.v2.model.IProductsModel;
import com.blo.sales.v2.model.ISaleDeletedDetailModel;
import com.blo.sales.v2.model.ISaleProductModel;
import com.blo.sales.v2.model.ISalesModel;
import com.blo.sales.v2.model.IStockPricesHistoryModel;
import com.blo.sales.v2.model.ITopUpModel;
import com.blo.sales.v2.model.IUserModel;
import com.blo.sales.v2.model.impl.ActivesCostsModelImpl;
import com.blo.sales.v2.model.impl.CashboxModelImpl;
import com.blo.sales.v2.model.impl.CashboxesActivesCostsModelImpl;
import com.blo.sales.v2.model.impl.CashboxesSalesModelImpl;
import com.blo.sales.v2.model.impl.CategoriesModelImpl;
import com.blo.sales.v2.model.impl.DBTransactionManagerModelImpl;
import com.blo.sales.v2.model.impl.DebtorsModelImpl;
import com.blo.sales.v2.model.impl.DebtorsSalesModelImpl;
import com.blo.sales.v2.model.impl.HistoryModelImpl;
import com.blo.sales.v2.model.impl.MobileCompanyModelImpl;
import com.blo.sales.v2.model.impl.PricesHistoryModelImpl;
import com.blo.sales.v2.model.impl.ProductsModelImpl;
import com.blo.sales.v2.model.impl.SaleDeletedDetailModelImpl;
import com.blo.sales.v2.model.impl.SaleProductModelImpl;
import com.blo.sales.v2.model.impl.SalesModelImpl;
import com.blo.sales.v2.model.impl.StockPricesHistoryModelImpl;
import com.blo.sales.v2.model.impl.TopUpModelImpl;
import com.blo.sales.v2.model.impl.UserModelImpl;
import com.blo.sales.v2.model.mapper.ActiveCostEntityMapper;
import com.blo.sales.v2.model.mapper.CashboxDetailEntityMapper;
import com.blo.sales.v2.model.mapper.CashboxEntityMapper;
import com.blo.sales.v2.model.mapper.CashboxSaleDetailEntityMapper;
import com.blo.sales.v2.model.mapper.CashboxSaleEntityMapper;
import com.blo.sales.v2.model.mapper.CashboxesActivesCostsEntityMapper;
import com.blo.sales.v2.model.mapper.CategoryEntityMapper;
import com.blo.sales.v2.model.mapper.DebtorDetailEntityMapper;
import com.blo.sales.v2.model.mapper.DebtorEntityMapper;
import com.blo.sales.v2.model.mapper.DebtorSaleEntityMapper;
import com.blo.sales.v2.model.mapper.MobileCompanyEntityMapper;
import com.blo.sales.v2.model.mapper.MovementDetailEntityMapper;
import com.blo.sales.v2.model.mapper.MovementEntityMapper;
import com.blo.sales.v2.model.mapper.NoteEntityMapper;
import com.blo.sales.v2.model.mapper.PaymentTypeInfoEntityMapper;
import com.blo.sales.v2.model.mapper.PriceHistoryEntityMapper;
import com.blo.sales.v2.model.mapper.ProductEntityMapper;
import com.blo.sales.v2.model.mapper.SaleAndProductEntityMapper;
import com.blo.sales.v2.model.mapper.SaleDeletedDetailEntityMapper;
import com.blo.sales.v2.model.mapper.SaleEntityMapper;
import com.blo.sales.v2.model.mapper.SaleProductEntityMapper;
import com.blo.sales.v2.model.mapper.StockPriceHistoryEntityMapper;
import com.blo.sales.v2.model.mapper.StockPricesHistoryEntityMapper;
import com.blo.sales.v2.model.mapper.TopUpEntityMapper;
import com.blo.sales.v2.model.mapper.UserEntityMapper;
import com.blo.sales.v2.model.mapper.UserLoggedEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperActivesCostsEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperCashboxesDetailsEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperCashboxesEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperCashboxesSalesDetailEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperCategoriesEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperDebtorsDetailsEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperDebtorsEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperDebtorsSalesEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperMobilesCompaniesEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperMovementsDetailEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperNotesEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperProductsEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperSaleStockEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperSalesAndStockEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperSalesEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperStockPricesHistoryEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperTopUpsEntityMapper;
import com.blo.sales.v2.view.mappers.CategoryMapper;
import com.blo.sales.v2.view.mappers.DebtorMapper;
import com.blo.sales.v2.view.mappers.DebtorSaleMapper;
import com.blo.sales.v2.view.mappers.LoggedInUserMapper;
import com.blo.sales.v2.view.mappers.PojoActiveCostMapper;
import com.blo.sales.v2.view.mappers.PojoCashboxDetailMapper;
import com.blo.sales.v2.view.mappers.PojoCashboxMapper;
import com.blo.sales.v2.view.mappers.PojoCashboxSaleDetailMapper;
import com.blo.sales.v2.view.mappers.PojoDebtorDetailMapper;
import com.blo.sales.v2.view.mappers.PojoMobileCompanyMapper;
import com.blo.sales.v2.view.mappers.PojoMovementDetailMapper;
import com.blo.sales.v2.view.mappers.PojoNoteMapper;
import com.blo.sales.v2.view.mappers.PojoPaymentTypeInfoMapper;
import com.blo.sales.v2.view.mappers.PojoPriceHistoryMapper;
import com.blo.sales.v2.view.mappers.PojoSaleAndProductMapper;
import com.blo.sales.v2.view.mappers.PojoSaleMapper;
import com.blo.sales.v2.view.mappers.PojoSaleProductDataMapper;
import com.blo.sales.v2.view.mappers.PojoSaleProductMapper;
import com.blo.sales.v2.view.mappers.PojoStockPriceHistoryMapper;
import com.blo.sales.v2.view.mappers.PojoTopUpMapper;
import com.blo.sales.v2.view.mappers.ProductMapper;
import com.blo.sales.v2.view.mappers.UserMapper;
import com.blo.sales.v2.view.mappers.WrapperDebtorsMapper;
import com.blo.sales.v2.view.mappers.WrapperDebtorsSalesMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoActivesCostsMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoCashboxesDetailsMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoCashboxesMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoCashboxesSalesDetailMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoCategoriesMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoDebtorsDetailsMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoMobilesCompaniesMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoMovementsDetailMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoNotesMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoProductsMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoSalesAndStockMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoStockPriceHistoryMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoTopUpsMapper;
import com.google.inject.AbstractModule;
import jakarta.inject.Singleton;
import com.blo.sales.v2.model.IDBTransactionManagerModel;
import com.blo.sales.v2.model.IDebtorSettlementsModel;
import com.blo.sales.v2.model.IFinancialHistoryModel;
import com.blo.sales.v2.model.impl.AccountsModelImpl;
import com.blo.sales.v2.model.impl.DebtorSettlementsModelImpl;
import com.blo.sales.v2.model.impl.FinancialHistoryModelImpl;
import com.blo.sales.v2.model.mapper.AccountEntityMapper;
import com.blo.sales.v2.model.mapper.DebtorSaleProductInfoEntityMapper;
import com.blo.sales.v2.model.mapper.DebtorSettlementEntityMapper;
import com.blo.sales.v2.model.mapper.FinancialMovementEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperDebtorSettlementEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperFinancialMovementEntityMapper;
import com.blo.sales.v2.model.mapper.WrapperSalesDeletedDetailsEntityMapper;
import com.blo.sales.v2.view.mappers.PojoAccountMapper;
import com.blo.sales.v2.view.mappers.PojoDebtSettlementMapper;
import com.blo.sales.v2.view.mappers.PojoFinancialMovementMapper;
import com.blo.sales.v2.view.mappers.PojoSaleDeletedDetailMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoDebtorSettlementsMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoFinancialHistoryMapper;
import com.blo.sales.v2.view.mappers.WrapperPojoSalesDeletedDetailsMapper;

public class BloSalesV2SingletonConfig extends AbstractModule {

    @Override
    protected void configure() {
        // --- VINCULACIÓN DE CONTROLADORES ---
        /**
         * controller
         */
        bind(IActivesCostsController.class).to(ActivesCostsControllerImpl.class).in(Singleton.class);
        bind(ICashboxController.class).to(CashboxControllerImpl.class).in(Singleton.class);
        bind(ICashboxesActivesCostsController.class).to(CashboxesActivesCostsControllerImpl.class).in(Singleton.class);
        bind(ICashboxesSalesController.class).to(CashboxesSalesControllerImpl.class).in(Singleton.class);
        bind(ICategoriesController.class).to(CategoriesControllerImpl.class).in(Singleton.class);
        bind(IDebtorsController.class).to(DebtorsControllerImpl.class).in(Singleton.class);
        bind(IDebtorsSalesController.class).to(DebtorsSalesControllerImpl.class).in(Singleton.class);
        bind(IHistoryController.class).to(HistoryControllerImpl.class).in(Singleton.class);
        bind(IMobileCompanyController.class).to(MobileCompanyControllerImpl.class).in(Singleton.class);
        bind(IPricesHistoryController.class).to(PricesHistoryControllerImpl.class).in(Singleton.class);
        bind(IProductsController.class).to(ProductsControllerImpl.class).in(Singleton.class);
        bind(ISaleDeletedDetailController.class).to(SaleDeletedDetailControllerImpl.class).in(Singleton.class);
        bind(ISalesController.class).to(SalesControllerImpl.class).in(Singleton.class);
        bind(ISalesProductController.class).to(SalesProductControllerImpl.class).in(Singleton.class);
        bind(IStockPricesHistoryController.class).to(StockPricesHistoryControllerImpl.class).in(Singleton.class);
        bind(ITopUpsController.class).to(TopUpsControllerImpl.class).in(Singleton.class);
        bind(IUserController.class).to(UserControllerImpl.class).in(Singleton.class);
        bind(IDBTransactionManagerController.class).to(DBTransactionManagerControllerImpl.class).in(Singleton.class);
        bind(IDebtorSettlementsController.class).to(DebtorSettlementsControllerImpl.class).in(Singleton.class);
        bind(IAccountsController.class).to(AccountsControllerImpl.class).in(Singleton.class);
        bind(IFinancialHistoryController.class).to(FinancialHistoryControllerImpl.class).in(Singleton.class);

        /**
         * models
         */
        bind(IActivesCostsModel.class).to(ActivesCostsModelImpl.class).in(Singleton.class);
        bind(ICashboxModel.class).to(CashboxModelImpl.class).in(Singleton.class);
        bind(ICashboxesActivesCostsModel.class).to(CashboxesActivesCostsModelImpl.class).in(Singleton.class);
        bind(ICashboxesSalesModel.class).to(CashboxesSalesModelImpl.class).in(Singleton.class);
        bind(ICategoriesModel.class).to(CategoriesModelImpl.class).in(Singleton.class);
        bind(IDebtorsModel.class).to(DebtorsModelImpl.class).in(Singleton.class);
        bind(IDebtorsSalesModel.class).to(DebtorsSalesModelImpl.class).in(Singleton.class);
        bind(IHistoryModel.class).to(HistoryModelImpl.class).in(Singleton.class);
        bind(IMobileCompanyModel.class).to(MobileCompanyModelImpl.class).in(Singleton.class);
        bind(IPricesHistoryModel.class).to(PricesHistoryModelImpl.class).in(Singleton.class);
        bind(IProductsModel.class).to(ProductsModelImpl.class).in(Singleton.class);
        bind(ISaleDeletedDetailModel.class).to(SaleDeletedDetailModelImpl.class).in(Singleton.class);
        bind(ISaleProductModel.class).to(SaleProductModelImpl.class).in(Singleton.class);
        bind(ISalesModel.class).to(SalesModelImpl.class).in(Singleton.class);
        bind(IStockPricesHistoryModel.class).to(StockPricesHistoryModelImpl.class).in(Singleton.class);
        bind(ITopUpModel.class).to(TopUpModelImpl.class).in(Singleton.class);
        bind(IUserModel.class).to(UserModelImpl.class).in(Singleton.class);
        bind(IDBTransactionManagerModel.class).to(DBTransactionManagerModelImpl.class).in(Singleton.class);
        bind(IDebtorSettlementsModel.class).to(DebtorSettlementsModelImpl.class).in(Singleton.class);
        bind(IAccountsModel.class).to(AccountsModelImpl.class).in(Singleton.class);
        bind(IFinancialHistoryModel.class).to(FinancialHistoryModelImpl.class).in(Singleton.class);

        bind(CategoryMapper.class).in(Singleton.class);
        bind(DebtorMapper.class).in(Singleton.class);
        bind(DebtorSaleMapper.class).in(Singleton.class);
        bind(LoggedInUserMapper.class).in(Singleton.class);
        bind(PojoActiveCostMapper.class).in(Singleton.class);
        bind(PojoCashboxDetailMapper.class).in(Singleton.class);
        bind(PojoCashboxMapper.class).in(Singleton.class);
        bind(PojoCashboxSaleDetailMapper.class).in(Singleton.class);
        bind(PojoDebtorDetailMapper.class).in(Singleton.class);
        bind(PojoMobileCompanyMapper.class).in(Singleton.class);
        bind(PojoMovementDetailMapper.class).in(Singleton.class);
        bind(PojoNoteMapper.class).in(Singleton.class);
        bind(PojoPriceHistoryMapper.class).in(Singleton.class);
        bind(PojoSaleAndProductMapper.class).in(Singleton.class);
        bind(PojoSaleMapper.class).in(Singleton.class);
        bind(PojoSaleProductDataMapper.class).in(Singleton.class);
        bind(PojoSaleProductMapper.class).in(Singleton.class);
        bind(PojoStockPriceHistoryMapper.class).in(Singleton.class);
        bind(PojoTopUpMapper.class).in(Singleton.class);
        bind(ProductMapper.class).in(Singleton.class);
        bind(UserMapper.class).in(Singleton.class);
        bind(WrapperDebtorsMapper.class).in(Singleton.class);
        bind(WrapperDebtorsSalesMapper.class).in(Singleton.class);
        bind(WrapperPojoActivesCostsMapper.class).in(Singleton.class);
        bind(WrapperPojoCashboxesDetailsMapper.class).in(Singleton.class);
        bind(WrapperPojoCashboxesSalesDetailMapper.class).in(Singleton.class);
        bind(WrapperPojoCashboxesMapper.class).in(Singleton.class);
        bind(WrapperPojoCategoriesMapper.class).in(Singleton.class);
        bind(WrapperPojoDebtorsDetailsMapper.class).in(Singleton.class);
        bind(WrapperPojoMobilesCompaniesMapper.class).in(Singleton.class);
        bind(WrapperPojoMovementsDetailMapper.class).in(Singleton.class);
        bind(WrapperPojoNotesMapper.class).in(Singleton.class);
        bind(WrapperPojoProductsMapper.class).in(Singleton.class);
        bind(WrapperPojoSalesAndStockMapper.class).in(Singleton.class);
        bind(WrapperPojoStockPriceHistoryMapper.class).in(Singleton.class);
        bind(WrapperPojoTopUpsMapper.class).in(Singleton.class);
        bind(PojoSaleDeletedDetailMapper.class).in(Singleton.class);
        bind(WrapperPojoSalesDeletedDetailsMapper.class).in(Singleton.class);
        bind(PojoDebtSettlementMapper.class).in(Singleton.class);
        bind(WrapperPojoDebtorSettlementsMapper.class).in(Singleton.class);
        bind(PojoFinancialMovementMapper.class).in(Singleton.class);
        bind(WrapperPojoFinancialHistoryMapper.class).in(Singleton.class);
        bind(PojoAccountMapper.class).in(Singleton.class);
        
        bind(ActiveCostEntityMapper.class).in(Singleton.class);
        bind(CashboxDetailEntityMapper.class).in(Singleton.class);
        bind(CashboxEntityMapper.class).in(Singleton.class);
        bind(CashboxSaleDetailEntityMapper.class).in(Singleton.class);
        bind(CashboxSaleEntityMapper.class).in(Singleton.class);
        bind(CashboxesActivesCostsEntityMapper.class).in(Singleton.class);
        bind(CategoryEntityMapper.class).in(Singleton.class);
        bind(DebtorDetailEntityMapper.class).in(Singleton.class);
        bind(DebtorEntityMapper.class).in(Singleton.class);
        bind(DebtorSaleEntityMapper.class).in(Singleton.class);
        bind(MobileCompanyEntityMapper.class).in(Singleton.class);
        bind(MovementDetailEntityMapper.class).in(Singleton.class);
        bind(MovementEntityMapper.class).in(Singleton.class);
        bind(NoteEntityMapper.class).in(Singleton.class);
        bind(PriceHistoryEntityMapper.class).in(Singleton.class);
        bind(ProductEntityMapper.class).in(Singleton.class);
        bind(SaleAndProductEntityMapper.class).in(Singleton.class);
        bind(SaleDeletedDetailEntityMapper.class).in(Singleton.class);
        bind(SaleEntityMapper.class).in(Singleton.class);
        bind(SaleProductEntityMapper.class).in(Singleton.class);
        bind(StockPriceHistoryEntityMapper.class).in(Singleton.class);
        bind(StockPricesHistoryEntityMapper.class).in(Singleton.class);
        bind(TopUpEntityMapper.class).in(Singleton.class);
        bind(UserEntityMapper.class).in(Singleton.class);
        bind(UserLoggedEntityMapper.class).in(Singleton.class);
        bind(WrapperActivesCostsEntityMapper.class).in(Singleton.class);
        bind(WrapperCashboxesDetailsEntityMapper.class).in(Singleton.class);
        bind(WrapperCashboxesEntityMapper.class).in(Singleton.class);
        bind(WrapperCashboxesSalesDetailEntityMapper.class).in(Singleton.class);
        bind(WrapperCategoriesEntityMapper.class).in(Singleton.class);
        bind(WrapperDebtorsDetailsEntityMapper.class).in(Singleton.class);
        bind(WrapperDebtorsEntityMapper.class).in(Singleton.class);
        bind(WrapperDebtorsSalesEntityMapper.class).in(Singleton.class);
        bind(WrapperMobilesCompaniesEntityMapper.class).in(Singleton.class);
        bind(WrapperMovementsDetailEntityMapper.class).in(Singleton.class);
        bind(WrapperNotesEntityMapper.class).in(Singleton.class);
        bind(WrapperProductsEntityMapper.class).in(Singleton.class);
        bind(WrapperSaleStockEntityMapper.class).in(Singleton.class);
        bind(WrapperSalesAndStockEntityMapper.class).in(Singleton.class);
        bind(WrapperSalesEntityMapper.class).in(Singleton.class);
        bind(WrapperStockPricesHistoryEntityMapper.class).in(Singleton.class);
        bind(WrapperTopUpsEntityMapper.class).in(Singleton.class);
        bind(PojoPaymentTypeInfoMapper.class).in(Singleton.class);
        bind(PaymentTypeInfoEntityMapper.class).in(Singleton.class);
        bind(WrapperSalesDeletedDetailsEntityMapper.class).in(Singleton.class);
        bind(DebtorSaleProductInfoEntityMapper.class).in(Singleton.class);
        bind(DebtorSettlementEntityMapper.class).in(Singleton.class);
        bind(WrapperDebtorSettlementEntityMapper.class).in(Singleton.class);
        bind(AccountEntityMapper.class).in(Singleton.class);
        bind(FinancialMovementEntityMapper.class).in(Singleton.class);
        bind(WrapperFinancialMovementEntityMapper.class).in(Singleton.class);
    }
}
