app.version=${project.version}

app.products.id-payment-product=1
app.products.top-up-comission=494
app.products.top-up-product=522

app.paymnts.comission-rate=1.05

db.url=jdbc:mysql://127.0.0.1:3306/blo-sales-v2
db.username=root
db.password=password
db.driver=com.mysql.cj.jdbc.Driver